export async function getUrlContent({ url }: { url: string }) {
  const response = await fetch(url);

  if (!response.ok) {
    return {
      supervisor:
        "If the error is retryable, try again. If not, tell the user why this failed.",
      message: `Failed to fetch ${url}: ${response.statusText}`,
      response,
    };
  }

  const html = await response.text();

  return {
    body: html.replace(/<(?!a\s|\/a\s|a>|\/a>)[^>]*>/g, ""),
  };
}

export async function generatePage({ markdown }: { markdown: string }) {
  const html = `
  <html>
    <head>
      <title>Hacker News Page Generated by Inferable</title>
      <script src="https://unpkg.com/showdown/dist/showdown.min.js"></script>
    </head>
    <body>
      <div id="content">${markdown}</div>
      <script>
        const converter = new showdown.Converter();
        document.getElementById("content").innerHTML = converter.makeHtml(document.getElementById("content").innerHTML);
      </script>
    </body>
  </html>
  `;

  const tmpPath = require("path").join(
    require("os").tmpdir(),
    "inferable-hacker-news.html",
  );

  await require("fs").promises.writeFile(tmpPath, html);

  return {
    message: `Tell the user to open the file at tmpPath in their browser.`,
    tmpPath,
  };
}
