FROM node:20

WORKDIR /app

COPY --link package.json ./
COPY --link package-lock.json ./

RUN npm ci

COPY machine.ts ./
COPY entrypoint.sh ./

RUN npm install -g tsx

ENTRYPOINT ["bash", "./entrypoint.sh"]
